### ISSUE TITLE
On 1.17 there is a networking crash with fabric API

### ISSUE THREAD

**Issue by Mythbusters123** [gnembon/fabric-carpet#974]
I don't know why this is but it only happens when I am using carpet. https://paste.ee/p/6AG6U#GeoilTIAMwEKVPGeUlGNR6iMbS1LL18d

**Comment by gnembon** [comment]
should be resolved in the next release

**Comment by Mythbusters123** [comment]
It seems to be conflicting with fabric-api which I need for some mods. Thank you!

**Comment by James103** [comment]
> should be resolved in the next release

Have you tried this with the develop release jar for Carpet mod (without `-sources` or `-dev`) located at https://github.com/gnembon/fabric-carpet/suites/3125192119/artifacts/71638136?

**Comment by gnembon** [comment]
Release rc-1 .42 doesn't have this problem

**Comment by Mythbusters123** [comment]
I just tried it again with fabric API 0.36+1.17 and it still crashes. Same error as before

**Comment by James103** [comment]
Copied logs from linked paste as the paste has an expiration date.

<details>

<summary> Minecraft Log </summary>

```
[10:35:14] [main/INFO]: Loading for game Minecraft 1.17
[10:35:14] [main/INFO]: [FabricLoader] Loading 11 mods:
	- carpet@1.4.42
	- carpet-extra@1.4.40
	- fabric-resource-loader-v0@0.4.7+b7ab6121d5
	- fabricloader@0.11.6
	- itemscroller@0.15.0-dev.20210630.181347
	- java@16
	- litematica@0.0.0-dev.20210630.180740
	- malilib@0.10.0+dev.22
	- minecraft@1.17
	- minihud@0.19.0-dev.20210626.193015
	- tweakeroo@0.10.0-dev.20210630.181035
[10:35:14] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/home/myth/.local/share/multimc/libraries/net/fabricmc/sponge-mixin/0.9.4+mixin.0.8.2/sponge-mixin-0.9.4+mixin.0.8.2.jar Service=Knot/Fabric Env=CLIENT
[10:35:14] [main/INFO]: Compatibility level set to JAVA_16
[10:35:16] [main/WARN]: @ModifyConstant conflict. Skipping mixins.tweakeroo.json:MixinStructureBlockBlockEntity->@ModifyConstant::overrideMaxSize(I)I with priority 999, already redirected by carpet.mixins.json:StructureBlockBlockEntity_limitsMixin->@ModifyConstant::negativeLimit(I)I with priority 1000
[10:35:16] [main/WARN]: @ModifyConstant conflict. Skipping mixins.tweakeroo.json:MixinStructureBlockBlockEntity->@ModifyConstant::overrideMaxSize(I)I with priority 999, already redirected by carpet.mixins.json:StructureBlockBlockEntity_limitsMixin->@ModifyConstant::positiveLimit(I)I with priority 1000
[10:35:16] [main/WARN]: @ModifyConstant conflict. Skipping mixins.tweakeroo.json:MixinStructureBlockBlockEntity->@ModifyConstant::overrideMaxSize(I)I with priority 999, already redirected by carpet.mixins.json:StructureBlockBlockEntity_limitsMixin->@ModifyConstant::negativeLimit(I)I with priority 1000
[10:35:16] [main/WARN]: @ModifyConstant conflict. Skipping mixins.tweakeroo.json:MixinStructureBlockBlockEntity->@ModifyConstant::overrideMaxSize(I)I with priority 999, already redirected by carpet.mixins.json:StructureBlockBlockEntity_limitsMixin->@ModifyConstant::positiveLimit(I)I with priority 1000
[10:35:16] [main/WARN]: @ModifyConstant conflict. Skipping mixins.tweakeroo.json:MixinStructureBlockBlockEntity->@ModifyConstant::overrideMaxSize(I)I with priority 999, already redirected by carpet.mixins.json:StructureBlockBlockEntity_limitsMixin->@ModifyConstant::negativeLimit(I)I with priority 1000
[10:35:16] [main/WARN]: @ModifyConstant conflict. Skipping mixins.tweakeroo.json:MixinStructureBlockBlockEntity->@ModifyConstant::overrideMaxSize(I)I with priority 999, already redirected by carpet.mixins.json:StructureBlockBlockEntity_limitsMixin->@ModifyConstant::positiveLimit(I)I with priority 1000
[10:35:16] [main/WARN]: @ModifyConstant conflict. Skipping mixins.tweakeroo.json:MixinStructureBlockBlockEntity->@ModifyConstant::overrideMaxSize(I)I with priority 999, already redirected by carpet.mixins.json:StructureBlockBlockEntity_limitsMixin->@ModifyConstant::positiveLimit(I)I with priority 1000
[10:35:16] [main/WARN]: @ModifyConstant conflict. Skipping mixins.tweakeroo.json:MixinStructureBlockBlockEntity->@ModifyConstant::overrideMaxSize(I)I with priority 999, already redirected by carpet.mixins.json:StructureBlockBlockEntity_limitsMixin->@ModifyConstant::positiveLimit(I)I with priority 1000
[10:35:16] [main/WARN]: @ModifyConstant conflict. Skipping mixins.tweakeroo.json:MixinStructureBlockBlockEntity->@ModifyConstant::overrideMaxSize(I)I with priority 999, already redirected by carpet.mixins.json:StructureBlockBlockEntity_limitsMixin->@ModifyConstant::positiveLimit(I)I with priority 1000
[10:35:18] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[10:35:18] [Render thread/INFO]: Setting user: Mythbusters123
[10:35:19] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 build 10
[10:35:20] [Render thread/WARN]: ERROR : Couldn't load Narrator library : Unable to load library 'fliteWrapper':
libflite.so.1: cannot open shared object file: No such file or directory
libflite.so.1: cannot open shared object file: No such file or directory
Native library (linux-x86-64/libfliteWrapper.so) not found in resource path (/usr/share/multimc/jars/NewLaunch.jar:/home/myth/.local/share/multimc/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar:/home/myth/.local/share/multimc/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar:/home/myth/.local/share/multimc/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar:/home/myth/.local/share/multimc/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar:/home/myth/.local/share/multimc/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar:/home/myth/.local/share/multimc/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar:/home/myth/.local/share/multimc/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar:/home/myth/.local/share/multimc/libraries/com/mojang/blocklist/1.0.5/blocklist-1.0.5.jar:/home/myth/.local/share/multimc/libraries/com/mojang/patchy/2.1.6/patchy-2.1.6.jar:/home/myth/.local/share/multimc/libraries/com/github/oshi/oshi-core/5.7.4/oshi-core-5.7.4.jar:/home/myth/.local/share/multimc/libraries/net/java/dev/jna/jna/5.8.0/jna-5.8.0.jar:/home/myth/.local/share/multimc/libraries/net/java/dev/jna/jna-platform/5.8.0/jna-platform-5.8.0.jar:/home/myth/.local/share/multimc/libraries/org/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.jar:/home/myth/.local/share/multimc/libraries/org/apache/logging/log4j/log4j-slf4j18-impl/2.14.1/log4j-slf4j18-impl-2.14.1.jar:/home/myth/.local/share/multimc/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar:/home/myth/.local/share/multimc/libraries/com/mojang/javabridge/1.1.23/javabridge-1.1.23.jar:/home/myth/.local/share/multimc/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar:/home/myth/.local/share/multimc/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar:/home/myth/.local/share/multimc/libraries/com/google/guava/guava/21.0/guava-21.0.jar:/home/myth/.local/share/multimc/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar:/home/myth/.local/share/multimc/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar:/home/myth/.local/share/multimc/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar:/home/myth/.local/share/multimc/libraries/com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar:/home/myth/.local/share/multimc/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar:/home/myth/.local/share/multimc/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar:/home/myth/.local/share/multimc/libraries/com/mojang/authlib/2.3.31/authlib-2.3.31.jar:/home/myth/.local/share/multimc/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar:/home/myth/.local/share/multimc/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar:/home/myth/.local/share/multimc/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar:/home/myth/.local/share/multimc/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar:/home/myth/.local/share/multimc/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar:/home/myth/.local/share/multimc/libraries/org/apache/logging/log4j/log4j-api/2.14.1/log4j-api-2.14.1.jar:/home/myth/.local/share/multimc/libraries/org/apache/logging/log4j/log4j-core/2.14.1/log4j-core-2.14.1.jar:/home/myth/.local/share/multimc/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar:/home/myth/.local/share/multimc/libraries/net/fabricmc/intermediary/1.17/intermediary-1.17.jar:/home/myth/.local/share/multimc/libraries/net/fabricmc/tiny-mappings-parser/0.2.2.14/tiny-mappings-parser-0.2.2.14.jar:/home/myth/.local/share/multimc/libraries/net/fabricmc/sponge-mixin/0.9.4+mixin.0.8.2/sponge-mixin-0.9.4+mixin.0.8.2.jar:/home/myth/.local/share/multimc/libraries/net/fabricmc/tiny-remapper/0.4.2/tiny-remapper-0.4.2.jar:/home/myth/.local/share/multimc/libraries/net/fabricmc/access-widener/1.0.0/access-widener-1.0.0.jar:/home/myth/.local/share/multimc/libraries/net/fabricmc/fabric-loader-sat4j/2.3.5.4/fabric-loader-sat4j-2.3.5.4.jar:/home/myth/.local/share/multimc/libraries/com/google/jimfs/jimfs/1.2-fabric/jimfs-1.2-fabric.jar:/home/myth/.local/share/multimc/libraries/org/ow2/asm/asm/9.1/asm-9.1.jar:/home/myth/.local/share/multimc/libraries/org/ow2/asm/asm-analysis/9.1/asm-analysis-9.1.jar:/home/myth/.local/share/multimc/libraries/org/ow2/asm/asm-commons/9.1/asm-commons-9.1.jar:/home/myth/.local/share/multimc/libraries/org/ow2/asm/asm-tree/9.1/asm-tree-9.1.jar:/home/myth/.local/share/multimc/libraries/org/ow2/asm/asm-util/9.1/asm-util-9.1.jar:/home/myth/.local/share/multimc/libraries/net/fabricmc/fabric-loader/0.11.6/fabric-loader-0.11.6.jar:/home/myth/.local/share/multimc/libraries/com/mojang/minecraft/1.17/minecraft-1.17-client.jar)
[10:35:20] [Render thread/INFO]: Reloading ResourceManager: Default, Fabric Mods (Fabric Resource Loader (v0), MiniHUD, Carpet Extra, Tweakeroo, MaLiLib, Carpet Mod, Fabric Loader, Litematica, Item Scroller)
[10:35:20] [Render thread/WARN]: Unable to read property: east with value: false for blockstate: {Name:"minecraft:cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[10:35:20] [Render thread/WARN]: Unable to read property: south with value: false for blockstate: {Name:"minecraft:cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[10:35:20] [Render thread/WARN]: Unable to read property: north with value: false for blockstate: {Name:"minecraft:cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[10:35:20] [Render thread/WARN]: Unable to read property: west with value: false for blockstate: {Name:"minecraft:cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[10:35:20] [Render thread/WARN]: Unable to read property: east with value: false for blockstate: {Name:"minecraft:mossy_cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[10:35:20] [Render thread/WARN]: Unable to read property: south with value: false for blockstate: {Name:"minecraft:mossy_cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[10:35:20] [Render thread/WARN]: Unable to read property: north with value: false for blockstate: {Name:"minecraft:mossy_cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[10:35:20] [Render thread/WARN]: Unable to read property: west with value: false for blockstate: {Name:"minecraft:mossy_cobblestone_wall",Properties:{east:"false",north:"false",south:"false",up:"false",west:"false"}}
[10:35:24] [Render thread/INFO]: OpenAL initialized.
[10:35:24] [Render thread/INFO]: Sound engine started
[10:35:25] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[10:35:25] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[10:35:25] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[10:35:25] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[10:35:25] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[10:35:25] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[10:35:25] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[10:35:26] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[10:35:26] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[10:35:26] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[10:39:34] [Render thread/WARN]: Missing data pack Fabric Mods
[10:39:34] [Render thread/WARN]: @ModifyConstant conflict. Skipping mixins.tweakeroo.json:MixinCloneCommand->@ModifyConstant::getBlockCountLimit(I)I with priority 999, already redirected by carpet.mixins.json:CloneCommandMixin->@ModifyConstant::fillLimit(I)I with priority 1000
[10:39:34] [Render thread/WARN]: @ModifyConstant conflict. Skipping mixins.tweakeroo.json:MixinCloneCommand->@ModifyConstant::getBlockCountLimit(I)I with priority 999, already redirected by carpet.mixins.json:CloneCommandMixin->@ModifyConstant::fillLimit(I)I with priority 1000
[10:39:34] [Render thread/WARN]: @ModifyConstant conflict. Skipping mixins.tweakeroo.json:MixinFillCommand->@ModifyConstant::getBlockCountLimit(I)I with priority 999, already redirected by carpet.mixins.json:FillCommandMixin->@ModifyConstant::fillLimit(I)I with priority 1000
[10:39:34] [Render thread/WARN]: @ModifyConstant conflict. Skipping mixins.tweakeroo.json:MixinFillCommand->@ModifyConstant::getBlockCountLimit(I)I with priority 999, already redirected by carpet.mixins.json:FillCommandMixin->@ModifyConstant::fillLimit(I)I with priority 1000
[10:39:34] [Render thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[10:39:34] [Render thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[10:39:34] [Render thread/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[10:39:34] [Render thread/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[10:39:34] [Render thread/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[10:39:34] [Render thread/INFO]: Reloading ResourceManager: Default
[10:39:35] [Render thread/INFO]: Loaded 7 recipes
[10:39:35] [Render thread/INFO]: Loaded 1137 advancements
[10:39:35] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[10:39:36] [Render thread/FATAL]: Reported exception thrown!
net.minecraft.class_148: Starting integrated server
	at net.minecraft.class_437.method_25412(class_437.java:495) ~[intermediary-minecraft-1.17-client.jar:?]
	at net.minecraft.class_312.method_1601(class_312.java:94) ~[intermediary-minecraft-1.17-client.jar:?]
	at net.minecraft.class_312.method_22686(class_312.java:165) ~[intermediary-minecraft-1.17-client.jar:?]
	at net.minecraft.class_1255.execute(class_1255.java:101) ~[intermediary-minecraft-1.17-client.jar:?]
	at net.minecraft.class_312.method_22684(class_312.java:165) ~[intermediary-minecraft-1.17-client.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar:build 10]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) ~[lwjgl-glfw-3.2.2.jar:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:190) ~[intermediary-minecraft-1.17-client.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1142) ~[intermediary-minecraft-1.17-client.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:730) [intermediary-minecraft-1.17-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:217) [intermediary-minecraft-1.17-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) ~[fabric-loader-0.11.6.jar:0.9.4+mixin.0.8.2]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162) ~[fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154) ~[fabric-loader-0.11.6.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at net.minecraft.class_1132.<init>(class_1132.java:56) ~[intermediary-minecraft-1.17-client.jar:?]
	at net.minecraft.class_310.method_29603(class_310.java:2047) ~[intermediary-minecraft-1.17-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_29740(MinecraftServer.java:277) ~[intermediary-minecraft-1.17-client.jar:?]
	at net.minecraft.class_310.method_29610(class_310.java:2047) ~[intermediary-minecraft-1.17-client.jar:?]
	at net.minecraft.class_310.method_29606(class_310.java:1941) ~[intermediary-minecraft-1.17-client.jar:?]
	at net.minecraft.class_528$class_4272.method_20174(class_528.java:437) ~[intermediary-minecraft-1.17-client.jar:?]
	at net.minecraft.class_528$class_4272.method_20164(class_528.java:343) ~[intermediary-minecraft-1.17-client.jar:?]
	at net.minecraft.class_528$class_4272.method_25402(class_528.java:274) ~[intermediary-minecraft-1.17-client.jar:?]
	at net.minecraft.class_350.method_25402(class_350.java:359) ~[intermediary-minecraft-1.17-client.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:27) ~[intermediary-minecraft-1.17-client.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:94) ~[intermediary-minecraft-1.17-client.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:490) ~[intermediary-minecraft-1.17-client.jar:?]
	... 26 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method onQItem(Lnet/minecraft/class_2846;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V in carpet.mixins.json:ServerPlayNetworkHandler_scarpetEventsMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap fabric-carpet-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[sponge-mixin-0.9.4+mixin.0.8.2.jar:0.9.4+mixin.0.8.2]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) ~[fabric-loader-0.11.6.jar:0.9.4+mixin.0.8.2]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:162) ~[fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:154) ~[fabric-loader-0.11.6.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
	at net.minecraft.class_1132.<init>(class_1132.java:56) ~[intermediary-minecraft-1.17-client.jar:?]
	at net.minecraft.class_310.method_29603(class_310.java:2047) ~[intermediary-minecraft-1.17-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_29740(MinecraftServer.java:277) ~[intermediary-minecraft-1.17-client.jar:?]
	at net.minecraft.class_310.method_29610(class_310.java:2047) ~[intermediary-minecraft-1.17-client.jar:?]
	at net.minecraft.class_310.method_29606(class_310.java:1941) ~[intermediary-minecraft-1.17-client.jar:?]
	at net.minecraft.class_528$class_4272.method_20174(class_528.java:437) ~[intermediary-minecraft-1.17-client.jar:?]
	at net.minecraft.class_528$class_4272.method_20164(class_528.java:343) ~[intermediary-minecraft-1.17-client.jar:?]
	at net.minecraft.class_528$class_4272.method_25402(class_528.java:274) ~[intermediary-minecraft-1.17-client.jar:?]
	at net.minecraft.class_350.method_25402(class_350.java:359) ~[intermediary-minecraft-1.17-client.jar:?]
	at net.minecraft.class_4069.method_25402(class_4069.java:27) ~[intermediary-minecraft-1.17-client.jar:?]
	at net.minecraft.class_312.method_1611(class_312.java:94) ~[intermediary-minecraft-1.17-client.jar:?]
	at net.minecraft.class_437.method_25412(class_437.java:490) ~[intermediary-minecraft-1.17-client.jar:?]
	... 26 more
```

</details>
